### ISSUE TITLE
在Firefox中网页显示不正常

### ISSUE THREAD

**Issue by bhxch** [graueneko/aktools#1]
在最新版 Firefox 无插件的环境中进行的测试。两个相邻 flexbox 的 button 发生了重叠。升级计算，精英材料和干员材料三个页面都会出现这个问题。
![](https://raw.githubusercontent.com/bhxch/pic/pic/20190612115318.png)
![](https://raw.githubusercontent.com/bhxch/pic/pic/20190612115502.png)
![](https://raw.githubusercontent.com/bhxch/pic/pic/20190612115519.png)

**Comment by graueneko** [comment]
感谢反馈，已定位到这是我代码的问题，请待我安装火狐调试一下。

**Comment by graueneko** [comment]
651107e  已修复：[修复Firefox下按钮错位的问题。](https://github.com/graueneko/aktools/commit/651107e040040f865f300e6493829643d7382a9d)。

新版本正在推送中，稍后可以手动点击右上角更新按钮刷新页面，即可显示正常页面。

再次感谢。
