### ISSUE TITLE
自动导入改进计划

### ISSUE THREAD

**Issue by Luke-lujunxian** [graueneko/aktools#10]
一些未来的改进想法
- [ ] 给模型加载加一个进度条

- [x] 允许用户调整结果

- [ ] 鼠标悬停时显示结果来源

- [x] 改进模型

**Comment by graueneko** [comment]
你对这方面比较熟悉的话，应该用python没有问题吧？是否可以将识别功能迁移到服务器端，这样可以加快网页端加载（而且python库很全比js好用多了）。

我可以提供服务器。

**Comment by Luke-lujunxian** [comment]
其实这个模型本来就应该在后端运行，但是这样计算量，流量，并发需求都和用户量成正比，所以才转换为前端模型。如果这些都可以接受那后端其实是更好的选择，而且效率和效果都会比前端好。甚至之前训练的数字识别模型也可以用上。
不过模型如何作为后端处理请求我还没试过，不知道会出现什么问题

**Comment by graueneko** [comment]
主要是考虑到……现在这样后端转发也是要走服务器流量的，不如就全给迁移过去。前端只负责把图片预处理和压缩一下减少流量消耗。

模型这边只要提供一个入口函数，调用这个函数就能得到结果，实现起来就很容易了。

**Comment by Luke-lujunxian** [comment]
那就没问题了，可以转到后端去。具体怎么操作呢？
顺便，作者给出的数据是GPU下可以做到200+FPS，CPU没有给但是我估计可以20~

**Comment by graueneko** [comment]
纯CPU下，最好能以python包或者单文件的形式，入口函数最好是接收base64编码和一些必要元数据信息。

你可以开一个单独的repo，或者我在现在repo下开个分支？

**Comment by Luke-lujunxian** [comment]
我整一个吧，我打算在已有实现基础上修改一下

**Comment by Luke-lujunxian** [comment]
或者可以开一个Organization把前后端整合在一起？

**Comment by wordlesswind** [comment]
插个话

征得作者同意后，我将`labelImg`教程视频搬运到了Bilibili: https://www.bilibili.com/video/av58221619

可以更新一下 https://github.com/Luke-lujunxian/aktools/blob/auto-fillin/HOWTOHELP.md 插个教程链接。

**Comment by Luke-lujunxian** [comment]
@wordlesswind 感谢

**Comment by Luke-lujunxian** [comment]
@graueneko py接收的传入的图片应该是什么形式的？（现在写了base64）

**Comment by graueneko** [comment]
@Luke-lujunxian 最好是base64，没问题

**Comment by Luke-lujunxian** [comment]
@graueneko 服务器环境是linux吗？

**Comment by graueneko** [comment]
@Luke-lujunxian 是，Ubuntu 18.04

**Comment by Luke-lujunxian** [comment]
@graueneko 写好了，依赖在 `requirements.txt`里
https://github.com/Luke-lujunxian/aktools-backend

**Comment by graueneko** [comment]
已收到。
尝试加载时在libdarknet.so处遇到了segment fault，是不是系统版本问题？（纠正一下，是ubuntu 16.04）

**Comment by Luke-lujunxian** [comment]
我这边没办法复现……
有一个办法是安装[这个](https://pjreddie.com/darknet/install/)上面的教程编译一次darknet（注意GPU设定），将libdarknet.so和libdarknet.a替换掉。这应该能解决系统问题

**Comment by graueneko** [comment]
重编译后dartnet问题已解决。
但运行时遇到以下错误
```
        # yolo.py
        out_boxes, out_scores, out_classes = self.sess.run(
            [self.boxes, self.scores, self.classes],
            feed_dict={
                self.yolo_model.input: image_data,
                self.input_image_shape: [image.size[1], image.size[0]],
                K.learning_phase(): 0
            })
```
错误信息：
```
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
(416, 416, 3)
2019-07-15 14:35:47.572949: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2019-07-15 14:35:47.926760: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
: Unknown error 576544309
```
附上测试用仓库图：
![QQ图片20190705121512](https://user-images.githubusercontent.com/48706971/61199568-09ab1380-a711-11e9-9c02-6f944a343d3d.png)

**Comment by Luke-lujunxian** [comment]
我这边也出现了那两个带E的错误信息，但是结果看应该是不影响的，问题应该是出在那个`Unknown error 576544309`上。。。。这个问题我也没法调试（没任何信息
现在我打算把识别部分的Keras+Tensorflow替换成Darknet，看看能不能解决问题

**Comment by Luke-lujunxian** [comment]
@graueneko 改好了，不过那个PR之前没看见，如果出了问题得麻烦你再改一下了

**Comment by graueneko** [comment]
辛苦了~

上面的bug我调试darknet源程序找到原因了……因为我clone到win下再上传到服务器，因此文件权限和格式上都有问题，darknet加载参数时出错，要用dos2unix转换一下才能使用。

目前服务器已经可以使用`https://rest.graueneko.xyz/aktools/detect`，以POST方式传入
```
{ 'data': '__base64imagestr__' }
```
即可获取类似于
```
{"error": false, "itemList": [["MTL_SL_STRG2", 30, 0.9985211491584778], ["MTL_SL_STRG1", 20, 0.9984574317932129], ["MTL_SL_RUSH2", 24, 0.9936997890472412], ["MTL_SL_BOSS2", 86, 0.9908142685890198], ["MTL_SL_STRG4", 2, 0.984414279460907], ["MTL_SL_BOSS4", 3, 0.9834322333335876], ["MTL_SL_STRG3", 24, 0.9683249592781067], ["MTL_SL_G1", 16, 0.8586458563804626]
, ["MTL_SL_MANGANESE1", 19, 0.8471285700798035], ["MTL_SL_RMA7024", 11, 0.8184953927993774], ["MTL_SL_G4", 11, 0.81727534532547], ["MTL_ASC_GRD1", 12, 0.6975480914115906], ["MTL_SL_G2", 17, 0.5971457958221436], ["MTL_SL_IRON3", 16, 0.578870415687561]]}
```
的结果，如果服务器内部出错会error=true。

这周我有个deadline不一定有时间搞，会尽快完善上去~

**Comment by Luke-lujunxian** [comment]
灰猫也辛苦了~
其实使用darknet原生才是最好的选择，因为TF启动的时候请求内存啥的会花多很多时间。（之前因为写了一半就懒得改，这次反而给动力我去统一2333）
