### ISSUE TITLE
国内连接速度及其缓慢

### ISSUE THREAD

**Issue by 2211427551** [graueneko/aktools#100]
当我在尝试连接https://aktoolscn.graueneko.xyz/时，不使用代理服务器，开始加载到加载完成至少需要70s，使用位于洛杉矶的代理服务器，可加载。但还是至少需要60s。

**Comment by bbaa-bbaa** [comment]
此项目使用Service Worker进行缓存
除第一次加载外 后面均不需请求静态文件

**Comment by graueneko** [comment]
国内线路服务器在HK，前段时间大陆到 HK 网络出口出了点问题，所有经 HK 线路都收到了影响。
