### ISSUE TITLE
升级计算出错

### ISSUE THREAD

**Issue by i-c-a-t** [graueneko/aktools#102]
![1](https://user-images.githubusercontent.com/53009819/76952821-a3822a80-6948-11ea-83c9-325622f92bda.png)
我也不知道怎么说这个问题

**Comment by graueneko** [comment]
@i-c-a-t 应该是js的问题，不是严重问题，无需修复。

**Comment by 0x11111111** [comment]
![image](https://user-images.githubusercontent.com/45055747/77129759-2bbf1780-6a90-11ea-8104-dbcf60a9c29f.png)
升级计算页面
将“当前精英化”等级升为一级，“当前等级”升满。随后将“当前精英化”降级，“当前等级”不变，超出正常范围。选择计算出现问题。

**Comment by graueneko** [comment]
超出正常范围的难免会引起错误，正常使用中不会遇到，无需修复。
