### ISSUE TITLE
希望更改1星小车的稀有度权重

### ISSUE THREAD

**Issue by yuban01652** [graueneko/aktools#104]
咱想提个建议，因为游戏里小车看上去是1星，真实稀有度和4星是一致的。
希望在进行公开招募的排序时，能够在计算中把小车的稀有度权重调到4星的程度。
这样“支援”这种必出4星或是小车的tag就不会被小车给拖到排序的后面了。现在支援tag的排序比生存tag要靠后，感觉不太合理。
感谢大佬_(:з」∠)_

**Comment by graueneko** [comment]
我理解你的建议，这个以前也做过，效果并不是很好，所以撤销了。

等我再考虑下，可能后续会加一些按钮来提高小车的权重。

**Comment by yuban01652** [comment]
了解，大佬辛苦了_(:з」∠)_
