### ISSUE TITLE
【刷图规划】中无法保存【关卡选择】预设

### ISSUE THREAD

**Issue by Jumpmelon** [graueneko/aktools#105]
【刷图规划】中，【关卡选择】的【保存预设】功能仅会保存至浏览器关闭；重启浏览器后，保存的预设会消失。
浏览器：Firefox

**Comment by bbaa-bbaa** [comment]
我看看

**Comment by Jumpmelon** [comment]
> 
> 
> 我看看

好的，感谢。

**Comment by bbaa-bbaa** [comment]
firefox 75.0无法复现这个bug

**Comment by Jumpmelon** [comment]
> 
> 
> firefox 75.0无法复现这个bug

emmm 我这里刚刚更新到 75.0，bug 依旧存在，我再检查一下我的设置。

**Comment by bbaa-bbaa** [comment]
能告诉下你使用的预设名称吗 
使用自带的四个预设名称会在下次打开被替换掉

**Comment by Jumpmelon** [comment]
> 
> 
> 能告诉下你使用的预设名称吗
> 使用自带的四个预设名称会在下次打开被替换掉

预设名称是随便起的，叫 `1`，`qwq`，`100%`，关闭浏览器再打开后，都只剩下了自带的四个。

**Comment by bbaa-bbaa** [comment]
我这边也出现了预设丢失的问题
正在查找原因 可能需要一点时间

**Comment by Jumpmelon** [comment]
> 
> 
> 我这边也出现了预设丢失的问题
> 正在查找原因 可能需要一点时间

我这边通过修改我的设置，发现是一个 Firefox 扩展【网盘助手】的原因。关闭扩展后就正常了。
并且刚刚发现该扩展已经在 Firefox 下架了【捂脸】。

**Comment by bbaa-bbaa** [comment]
应该不是扩展的问题 我发现我少打了个this（捂脸

**Comment by Jumpmelon** [comment]
> 
> 
> 应该不是扩展的问题 我发现我少打了个this（捂脸

好的我这里打开扩展也正常了。非常感谢。😂

**Comment by bbaa-bbaa** [comment]
??? PR还没合并怎么正常的 就很玄学

**Comment by Jumpmelon** [comment]
> 
> 
> ??? PR还没合并怎么正常的 就很玄学

emmmmmmm 我刚才测试了一下现在确实好了..?? 有点奇怪 😂😱

**Comment by Jumpmelon** [comment]
> 
> 
> ??? PR还没合并怎么正常的 就很玄学

emm 我清空数据再来又不行了，玄学【捂脸】

**Comment by bbaa-bbaa** [comment]
等喵佬合并pr

**Comment by Jumpmelon** [comment]
> 
> 
> 等喵佬合并pr

好的，感谢 😂
