### ISSUE TITLE
发现网站支持PWA，请问是否有打算支持“快应用”呢

### ISSUE THREAD

**Issue by wordlesswind** [graueneko/aktools#11]
对相关内容不是很了解……只是问一下。
毕竟主流厂商都支持[快应用](https://www.quickapp.cn/)
虽然我就是非主流的那一个（逃）

**Comment by graueneko** [comment]
我还是第一次听说“快应用”，感谢提供信息。

粗略看了下，这类应用采用的是vue或者类似的框架，重构起来工作量很大，目前可能不会考虑。
