### ISSUE TITLE
对于精英材料，是否没有必要从最低级的材料开始合成？

### ISSUE THREAD

**Issue by FlandiaYingman** [graueneko/aktools#16]

**Comment by singer233** [comment]
我认为如果可以的话将精一材料从最低级材料开始合成。
但是精二材料的话就尽量从“可固定掉落的最高级”例如精英材料”聚酸脂组“就从“聚酸脂”这个会固定掉落的材料开始计算。

**Comment by mm615657** [comment]
记得有大佬算过材料合成是几乎没有亏损的，也就是打材料的效率完全取决于地图的材料掉落量。
如果这一点没问题的话那么材料合成本质上是用龙门币抽奖买材料的一个过程。个人觉得几百龙门币抽一次平均15%（具体取决于值班干员）的额外掉落还是比较划算的，所以自然是低级材料多多益善咯
