### ISSUE TITLE
页面导航栏右上角工具栏优化

### ISSUE THREAD

**Issue by w840980261** [graueneko/aktools#18]
右上角工具按钮建议增加title属性,在PC端访问时可以悬停提示功能
图片还可以再压缩小一点,首次进入特别慢

**Comment by w840980261** [comment]
在chrome移动窗口下页面溢出可左右拖动

**Comment by wordlesswind** [comment]
而且如果安装了Google 翻译的话，会触发翻译窗口。

**Comment by wordlesswind** [comment]
白边已修复 fd04f90cb59793489a75a03617141c550842a42b
