### ISSUE TITLE
收集到的反馈信息

### ISSUE THREAD

**Issue by Evealicemier** [graueneko/aktools#2]
1.精英材料可以尝试和干员材料合并，自动跳转，现有精英材料名目改为仓储材料，放在最后一栏

2.【精英材料】重新按照稀有度排列材料，将芯片和技能书放置到最后，适应游戏内排列方式……

3.希望加入干员头像

4.导出功能

关于精英材料和干员材料的看法：
一般逻辑上，一般人的逻辑是这样的
已有/我已有干员→我想要弄的干员→还需要素材（包括已有对比）【一般到这边结束】→规划路径【隐藏】
现在是
已有【但是有需要的选项可以填】→干员情况→↓
····························· ↑←←←←←←←←←←←←←←←←↓
【这个时候是】已有+(包括已有的）总需求→ 规划路径【把这个作为重点】

**Comment by graueneko** [comment]
1. 这个没有必要；
2. 在考虑范围内，但按稀有度排序和游戏内排序是两种**冲突**的排序方式：游戏内并非按稀有度排序；
3. 近期会加入；
4. 暂时没想到什么场景需要导出？材料规划部份已有复制导出功能。

实际预期的精英材料用法有两种：
1. 需要材料，进入材料计算器，计算；
2. 想知道把某干员精英化/升级技能需要材料，填好，导入，计算
而非先写好库存再查询。

**Comment by Evealicemier** [comment]
关于
1.建议把精英材料和干员表前后顺序倒一下，以免造成困难，或者在首页加入导航
2.可以尝试可切换的排序方式……
3.谢谢
4.跨平台使用，从手机到电脑（模拟器），有人希望自己在电脑上填写之后手机上一样可以直接导入查看

**Comment by defEdYs** [comment]
灰猫博士过于有能 辛苦辛苦 最近在使用过程里有以下的感受和一些建议：

1.
不知道是否有细化刷图规划的动向呢？鉴于预期使用方法中有干员培养为导向的导入方式，
是否可以在详细规划的function中加入“经验本次数”“钱本次数”一并计算？虽然是有升级计算器，
但整体统筹起来也许会显得更加一目了然。
另外，刷图掉落经验的副产物确实非常随机难以计算 
不过如果把刷材料固定的龙门币收入一起计算 也就能把整体培养过程中刷钱本的次数降下来。

2.
个人也有在玩少前 少前里的重装培养系统 有一种类似于拼拼图的玩法：
在特殊形状的拼图版里嵌入不同的芯片，来提高重装部队的属性。
通过一个叫做AK12芯片计算器的工具，可以计算出拼图的最优解，而这种工具可以利用局域网代理端口获取游戏中已有的芯片。所以我想是否在arktools上也能存在这种功能
（不过在现有游戏内容下貌似根本没有必要这么麻烦）
不知道舟游的通信请求是否加密 所以这种获取已有材料的方式也不知道能不能共通，所以冒昧地有这个提议，还请不要介意。

PS：
1.
个人使用的是IPhoneSE（和5S一样尺寸）
在实际使用过程中存在有“干员材料”界面无法显示“当前”“目标”词条下数字的BUG
以及“精英材料”“升级计算”界面下显示过于拥挤的问题
推测是由于UI和ICON固定大小的情况下 由于屏幕大小差异引起的问题？
2.添加到桌面的伪APP式沉浸体验相当舒服 大佬流批！

PS1中的附图
![image](https://user-images.githubusercontent.com/31523168/59568999-cdd64d00-9083-11e9-8d2e-793fd8e191b0.png)
![image](https://user-images.githubusercontent.com/31523168/59569002-d595f180-9083-11e9-9eac-6d8750e71731.png)
![image](https://user-images.githubusercontent.com/31523168/59569004-dd559600-9083-11e9-8c80-64729e33820b.png)

**Comment by defEdYs** [comment]
一些补充：
1 刚提到的AK12工具 如果需要 可以看这个链接 https://bbs.nga.cn/read.php?tid=17162135
2 考虑到实际功能基本一致 是否可以把ak站和aktools站合并起来？
3 ak站的复制链接跨平台用非常cool 也许也可以在aktools里用

**Comment by graueneko** [comment]
@defEdYs 1. 这点有加入计划，具体怎么做还没想好，如果有建议欢迎提出

2. 舟游通讯使用https，拦截需要安装根证书等破解手段，非常不安全，不合适

**Comment by graueneko** [comment]
@defEdYs iPhone5s屏幕下体验不佳非常抱歉，我自己用的是6s因此在设计时最低适配到了6/6s屏幕大小。之后会考虑添加一些选项来提升一下5s大小屏幕的显示

**Comment by graueneko** [comment]
@defEdYs ak站实际是为了部分网络不佳/功能需求不高的人保留的快速使用体验，暂无强制迁移意向（虽然新站用户量远低于老站）。

跨平台复制功能有在考虑，近期会加入。

**Comment by graueneko** [comment]
> 灰猫博士过于有能 辛苦辛苦 最近在使用过程里有以下的感受和一些建议：
> 
> 
> 不知道是否有细化刷图规划的动向呢？鉴于预期使用方法中有干员培养为导向的导入方式，
> 是否可以在详细规划的function中加入“经验本次数”“钱本次数”一并计算？虽然是有升级计算器，
> 但整体统筹起来也许会显得更加一目了然。
> 另外，刷图掉落经验的副产物确实非常随机难以计算
> 不过如果把刷材料固定的龙门币收入一起计算 也就能把整体培养过程中刷钱本的次数降下来。
> 
> 
> 个人也有在玩少前 少前里的重装培养系统 有一种类似于拼拼图的玩法：
> 在特殊形状的拼图版里嵌入不同的芯片，来提高重装部队的属性。
> 通过一个叫做AK12芯片计算器的工具，可以计算出拼图的最优解，而这种工具可以利用局域网代理端口获取游戏中已有的芯片。所以我想是否在arktools上也能存在这种功能
> （不过在现有游戏内容下貌似根本没有必要这么麻烦）
> 不知道舟游的通信请求是否加密 所以这种获取已有材料的方式也不知道能不能共通，所以冒昧地有这个提议，还请不要介意。
> 
> PS：
> 1.
> 个人使用的是IPhoneSE（和5S一样尺寸）
> 在实际使用过程中存在有“干员材料”界面无法显示“当前”“目标”词条下数字的BUG
> 以及“精英材料”“升级计算”界面下显示过于拥挤的问题
> 推测是由于UI和ICON固定大小的情况下 由于屏幕大小差异引起的问题？
> 2.添加到桌面的伪APP式沉浸体验相当舒服 大佬流批！
> 
> PS1中的附图
> ![image](https://user-images.githubusercontent.com/31523168/59568999-cdd64d00-9083-11e9-8d2e-793fd8e191b0.png)
> ![image](https://user-images.githubusercontent.com/31523168/59569002-d595f180-9083-11e9-9eac-6d8750e71731.png)
> ![image](https://user-images.githubusercontent.com/31523168/59569004-dd559600-9083-11e9-8c80-64729e33820b.png)

5s问题已修复，请更新使用 4520459

**Comment by lzhlzjly** [comment]
有个问题 公开招募选了词条以后 右上角的数值是什么意思呢，另外是否考虑做一个公开招募出率的统计呢

**Comment by KurohaLab** [comment]
大大辛苦！
一个微不足道的提议：可否在精英材料及其合成材料计算结束后增加以树状图显示的选项以增加条理性？

**Comment by graueneko** [comment]
@KurohaLab 有在考虑，但还没想好怎么加，加在哪。新建议最好单开issue~

**Comment by goethoe** [comment]
材料规划功能可能出现了问题
