### ISSUE TITLE
大佬下午好，斗胆提问有没有可能把升级需要的作战录像和金币都加到规划上

### ISSUE THREAD

**Issue by yyclovezyx** [graueneko/aktools#20]
大佬下午好，规划精英材料的功能真的是造福大众，不知道有没有可能把刷芯片的理智(PR-2次数)，刷胶水（AP-5次数）的理智和刷作战录像（LS5的次数）及龙门币（CE5的次数）的理智都算进去呢

**Comment by graueneko** [comment]
感谢建议，这些掉落相对固定的会考虑加到升级计算器里，应该不会添加在精英材料计算器。
