### ISSUE TITLE
请求在升级计算中加入每日基建生产的录像带和龙门币

### ISSUE THREAD

**Issue by NBOOK** [graueneko/aktools#21]
目前计算方法钱和经验完全来自于刷本，不太符合实际，通过加入基建产出可以得出达到目标的一个比较具体的时间，望考虑，谢谢。

**Comment by graueneko** [comment]
会考虑，但应该只会使用基础速度（+可选加速比率），可能不会很精确

**Comment by zodiacg** [comment]
同求。
我感觉加三个框，输入一下自己估计的每日经验和龙门币生产，以及准备完成该干员经验+龙门币囤积的天数，往总数里加一下就可以。
如果基建生产速率都要估计的话就太复杂了，有基建助手大部分人还是对自己的生产能力有个估计的。
