### ISSUE TITLE
不推荐使用 console.log 来检测错误，更不推荐在生产环境中 log

### ISSUE THREAD

**Issue by Misaka-0x447f** [graueneko/aktools#23]
如有debug需要，请考虑插入debugger;语句，就像这样：
```typescript
constructor() {
   const a = {};
   setA();
   debugger;
   this.a = a;
}
```
这种方法在 js + DOM Api 和 node.js 中均有效。
并且就算忘了去掉也没有问题，不打开开发人员工具的话就不会启用断点。

**Comment by graueneko** [comment]
谢谢建议。我本身不是做前端的，不了解debugger（又学到了新的东西），用console.log()只是为了方便。

后续会尽可能避免。
