### ISSUE TITLE
【尚无证据】Tag更新：现在 -近战位 -群攻 这两个tag可以岀阿消

### ISSUE THREAD

**Issue by Fogg-Wu** [graueneko/aktools#27]
在7小时40分，-近战位 -群攻 这两个tag不被划掉的情况下，使用加急许可的成果

**Comment by Fencess** [comment]
图或者视频呢，空口说我是不信的

**Comment by Fogg-Wu** [comment]
开箱的截图毫无意义，无法给出印证（故没有截图）

issue有些耸人听闻，所以我修改一下

**Comment by Fencess** [comment]
我都是9小时拉满的，近战位群攻都是艾斯黛儿或者被划掉，没有出过阿肖，还是持保留意见，等待更多例子

**Comment by Luke-lujunxian** [comment]
这个在NGA那边讨论会更有效吧？
