### ISSUE TITLE
可定制化的寻访模拟器

### ISSUE THREAD

**Issue by graueneko** [graueneko/aktools#3]
由于现在已有较多寻访模拟器，为避免重复造轮子，若实现新的寻访模拟器务必要有不同的特色。
目前对寻访模拟器的预期如下：
1. 可自定义up干员
2. 可自定义干员池

实际上，由于静态页面的限制，自定义参数只能通过Url Get Parameter或者Router参数实现。若采用这种方式，自定义干员池则会导致URL过长，因此[2]被排除在外不考虑，只考虑UP干员。

那么预期有两种页面和URL Scheme（实际未必一定这样）：
1. /recruit/generate ：寻访页面生成器；
2. /recruit/?id1,id2,id3,id4 ：寻访页面，自动判断ID对应的干员和星级，并生成对应up池。

**Comment by Misaka-0x447f** [comment]
可考虑维护一个内部的干员列表，然后用1bit保存该bit所在位置的对应干员的开关状态，得出一个十六进制数字作为参数。自定义干员池也可以通过这样的方式实现。
.........

不过有开舟游私服的需求么...如果没有的话现有模拟器依然能完全满足需要...

**Comment by graueneko** [comment]
@Misaka-0x447f 有些东西能不能做，不是技术上的问题……而是法律上的问题。

**Comment by graueneko** [comment]
@Misaka-0x447f 这个比特表示跟我想的一样，后面会这么做的，实现上应该会用base64编码
（咕咕咕

**Comment by Misaka-0x447f** [comment]
啊我的意思是，没觉得寻访模拟器有什么特别的用处，除非你打算开私服...
所以建议低优先级...

**Comment by graueneko** [comment]
是没什么用处，但可以给大家一个游戏之外的娱乐（大概？），也不会影响舟游本身。
优先级很低没错，所以至今没做…

**Comment by Misaka-0x447f** [comment]
您好，如果您需要游戏之外的娱乐的话我们推荐您游玩 webstorm 和 steam ，您也可以考虑开发理智恢复模拟器来降低开发成本（？

**Comment by graueneko** [comment]
短期内不会实现这个功能，暂且关闭。
