### ISSUE TITLE
精英材料中4-6掉落材料有问题

### ISSUE THREAD

**Issue by anvernuse** [graueneko/aktools#36]
4-6在游戏中是有全新装置的掉落的，但是精英材料计算器计算出来的4-6是没有全新装置的掉落，这个会对计算结果产生一些影响吧

**Comment by bbaa-bbaa** [comment]
物品材料貌似只统计常规材料的掉落
4-6的全新装置掉落属于额外物资，掉出概率相当低
据[企鹅物流数据统计](https://penguin-stats.io/result/item)，4-6掉出全新装置概率仅为1.47%
