### ISSUE TITLE
自动识别没有结果返回

### ISSUE THREAD

**Issue by Lucasgong** [graueneko/aktools#37]
感谢您做了这么方便的平台，但自动识别功能不能正常起作用。

在ipad平台和ios平台都分别截图并尝试识别，但点击开始识别均无任何反应。
在精英材料界面填好需求后，在自动导入界面点击保存并导入材料计算器显示材料为空，请先添加需求。

**Comment by Lucasgong** [comment]
看F12后，显示
Request URL: https://rest.graueneko.xyz:1443/aktools/detect
Request Method: POST
Status Code: 504 Gateway Timeout (from ServiceWorker)
Referrer Policy: no-referrer-when-downgrade

不知是不是图片过大导致的？

**Comment by graueneko** [comment]
@Lucasgong 是服务器故障，暂时没找到原因，已有dalao实现了一种不需要服务器的功能，可以尝试下

**Comment by Lucasgong** [comment]
谢谢您的回复。
bbaa-bbaa 大佬实现的那个吗？我在哪里可以试试呢？

**Comment by graueneko** [comment]
@Lucasgong 打开后刷新或者右上角更新后，多出来一个导入页面

**Comment by Lucasgong** [comment]
刚刚试了，可以很好的识别边界，但之后识别物品就一直没有反应。
在电脑，ipad，手机上都试过，一样的效果，不是性能的问题。
将图片截小，压缩到刚能识别边界的程度，也不行。

**Comment by bbaa-bbaa** [comment]
也许是我的问题
之前改了两行代码自信以为不会出现bug
你可以先试试![](https://aktools.bbaasite.cn)旧版本

**Comment by bbaa-bbaa** [comment]
> 刚刚试了，可以很好的识别边界，但之后识别物品就一直没有反应。
> 在电脑，ipad，手机上都试过，一样的效果，不是性能的问题。
> 将图片截小，压缩到刚能识别边界的程度，也不行。
事实上真的是我的问题
![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgwAAABRCAYAAAC+Cf4PAAAIM3pUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHjarZdrkispDoX/s4pZQoKEgOXwUsTsYJY/H+msqluP29G3o+2wnSZJkHSOjkTY//uvh//wSmI1aC7VmtnFS5u21Lmo1+v1+o2X3t+v17zSM/ppPOS3CYkh4Vdef22/fmNnPH88UPQZH5/HQ5nPOvVZ6GPh+yVn53O9HiOfhSS9xuPzP7TngW6/uPN80nyWfRb/+l8LwViZ9SSFtCXKdX+n106CFdKk81v5jmLpjBSu5f5Wad/jFx474k8BTOXn+F1vlslHOF4LvbllX+L0jMf8ZVzet0+fLIrpmZI+bjwAvBHhW/zcV3XfL++6WiBc9jj15uJ9xcRBOOV+zHgXPpnrcr8b73r1a4LawtURrsGfFhMR96hxxR497vt3xomJmnYq/KY0k9xjVUpqad6g6HlHTyWAzwKdJBPkhOH0bku8921nPzar7LwiM1NkMTD+/A5fB/7p+9NC7ofmMd5kLHessCsdfmHGQe58MwtAoj8xzXd8Y3j9XF9fB1gBwXyHueJgv8ZrifFKzxe35MZZrhyYqtcrX2JZzwKEiL0zxkQBgcui5GjxKimVGIljBZ+O5Uk0DRCIOeS0sDKpkAkl1XT25pkS77kpp9cw8gIQWYwkqSeBAEs1q5FvFQr1kCVrztlyyTW33E1MLZtZsaNTvUjRkouVUmpppVepWnO1WmqtrfaWmiBjOTRrpdXWWu9s2rWzVmd+Z2CkIUNHHjbKqKONPqHP1JmnzTLrbLOvtGQhAWHZKquutvqOGypt3XnbLrvutrvDNRdXz25evHrz/o7ag+pn1L4i99eoxQe1dAN15pUP1Bgu5W2JeOQkH8xALGkE8XIQgNDpYHbVqJoOcgezqyUJIjlhZT7grHgQA0HdMWWP79h9IPdb3ALR/VPc0k/IhQPdv4FcOND9gtx33H5AbfVbbuUG6GQhMUUhhfTzYqvHhlnX1Wbbw3OH6u54tbNiZuMaSRQ8k7pzLCNN9vY0OwInJVhx7ZaSrTp8kS4tg0Tx0cUTrvqVl59ML9dMisK1ssE7zrJH7VbAolWzGdZkC/Jx1Ev63lJT8WsN7xREq3tm37s6235sRNJ2nQhsEq8oXYM1HjJO2ERDd7OFKMGcnUGCgRLbbnpF+8VJe195yJw4areESgsV6ZDBKKaItyres9YRiXeUCQhzJxg7UpsYurwSaLCLgvPjlzgEApGFOOJ5bl4y4OSkjTV1ojW9X1mGx6FsRIz2dRuGdvkx8zQVL0PDm6V9TI8TEBrKRW6YkmDp8pwBo3tZcG0IO0RCu3qflVSaW6ztbcQ3qHxe+W3hNq4+ul51pIh7lK9U4BwaRmPyA8Ih9ZLjb27+yb3wTx/8ei/8G9ace+HLzUiemOg6XKL7miWVcRFNH0hGu+BOnqOolz5ldAeMSQRPivip4/Ua5azlcx8Rg2DrYn045WNlPWBUhbrJTgEqrdMIdPZiD+Zu9aShHvRiW1rLpfsyFkSxRnMz97F1mc6CoCEVa0aagynWYxzo3C40qvN0dzA1jL6sX8hU8tWKF57dMxUYInF5m64TDZlGF4O2rTZ8exP9uEQbdOgKGek0vMi7R2U6km0bCtZpyHrdXmUdNk7Ur9eh8yJvho8xkbxESlpWshKL6ukfWqwnP4njyyfyCa/ih4PEnzRNrZL2cowjrootZADFoc2N+JMa+OA0WWukRVL1jYaM2bW1U8n36ZGua49p5ELC1SHFlxP5j8sRkhHZupdtt7x2781YItJVkVc0VzUBAWElbfbICEAsirK2nj0N6zXjYLvWDCUf3XE94PFFHU/wqaH2qNpPe8MZAkA0jI4cu6kEkwoT1koxHe08Aur3uxvCVkY7IK5tCqUVVHm2RDaQ3S/vBexV13sUw1tEX+HN0vrybDiDPQgyVNhoAEE6Ggtn4F/GcIMT+LtPJco0xjXUE5hTRMtkd+NkQRnBOnhA7SiimTpGpfyJQooNOWWZTdCjsbOtQ3Rra0HAzl6HozZw5baKxm02GgFtdOSHMyVFEuCUB/Uxo2dIHKTHnjn2lEx2JckVwiDYaVGeLWVYSLKCkboYjm8dpJJTiyh+yNy2nhc1PUPIE1hgoIpQMbuStV2w0AUlvSpp7PsQetUfQWyX0nxUD0O6E+Ao1QBQFDjSLgvBP+k7cyY5yTapcw70flB0lNpaB6m4TkksgrS3GTZ7D7rVdoKaf0Md2qC8MjE4iUbNoyJQFGGa2mGOt7IC4jIwjmy4Y0IRInsW3UbVYcQSFbjDesz8IfWJl91JFNh2nsalTjyNgzZATz4WMIXuXcZCuACJrAW+ukj3AYHtQgVHInsuZ4tew++ysHf2QjjgWEYwJoci8KzJKMsNraRgggJYa2Gaczi+DudJw8yZVkaxQ2Fps55+lvLbKeGn/CvT5t2XlNk43d5/zqVG28SBunbqutLpJYqAsk0SgkO3wwmtN3VajG1ulIOK2FGIL+TkcHiWY1m/2UF7DIfwrs54NqeReXHzFHkb6JTmsUosSP90oW4MTkswnlqAC2S9TBpWyK0hZo6ITl9DC5ZUx2HJOPJsUin8dNCHOLvgLxWb4xBJ+VNMA7p7VHGctou4WUXBRkRWn8MtZ89TXsqiS8nEGaUiqhwiaYM56joaTzBTDrMSWjr6eNgO9Liw2PQ0EhVtp0UinffegzTa7TRPq4GOAScVFI5keEUkA8Xu9E5y9xrxxznPFJBD2Brs4YhGmKGWn0n33RLKtyf0We41fhf5181nM0Wyvk8Jf2PO35oS/nyZ4rTsLfwffNHBVQdVPIAAAAGEaUNDUElDQyBwcm9maWxlAAB4nH2RPUjDQBzFX1u1VSoKdhBxyFCdLIiKOGoVilAh1AqtOphc+gVNGpIUF0fBteDgx2LVwcVZVwdXQRD8AHFxdVJ0kRL/lxRaxHhw3I939x537wB/vcxUs2McUDXLSCXiQia7KgRfEUI/uiGgS2KmPieKSXiOr3v4+HoX41ne5/4cvUrOZIBPIJ5lumERbxBPb1o6533iCCtKCvE58ZhBFyR+5Lrs8hvngsN+nhkx0ql54gixUGhjuY1Z0VCJp4ijiqpRvj/jssJ5i7NarrLmPfkLwzltZZnrNIeRwCKWIFJHMqoooQwLMVo1UkykaD/u4R9y/CK5ZHKVwMixgApUSI4f/A9+d2vmJyfcpHAc6Hyx7Y8RILgLNGq2/X1s240TIPAMXGktf6UOzHySXmtp0SOgbxu4uG5p8h5wuQMMPumSITlSgKY/nwfez+ibssDALdCz5vbW3MfpA5CmrpI3wMEhMFqg7HWPd4fae/v3TLO/HxlHcoMEAUYqAAAABGdBTUEAALGPC/xhBQAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+MIEAklN2PykbUAABqaSURBVHja7d17WFTXvfDxbyrH8bEv48l7IOkJmsZbq2jAG0QlmCAmIKYgaQfJq0IqYF5l0go0hiGJDtFKTAMkcdS3oKYgHhF6pNBo8XiXeEOiDiqYopgo2B7hiYeZxjIKWe8fgKLcEbwkv8/zzPM4s69r7fXb+7fXXhsfUUophBBCCCHaYXfnD19eusw31/5Jff23UjtCCCGEAOCR5j0MX166TF39tzj826No+vaV2hFCCCEEAD9o/uWba/+UZEEIIYQQ7ScM9fXfSrIghBBCiPYTBiGEEEIISRiEEEIIIQmDEEIIISRhEEIIIYQkDEIIIYSQhEEIIYQQkjAIIYQQQhIGIYQQQkjCIIQQQgghCYMQQgghJGEQ99rfKi9JJQghhCQMQgghhBCSMAghhBDiu5owWHa+zXT/9ym49oDs0OV8YmM2UF738B14W/EaIpftoVpiQAghxP1JGGyU5y5jrq8HbhN9mGXM7eQFtZK02RNwGTsBF4+3KXjQL8K2Yla9sZ5+L+sYYtf0o5Xyg1msWKTDY+I80i72xIZ6p140LkHMsH5EVMpZbL1eWe3VS3fbywVSg5vqxYdZhixKO5NIVmcR/sKyxnq0cXSljunGPViaprk1rtPNg6mz32brOZucJYQQolcShrov2HYAXlmbz2efLmHk8Q8x5Vs7saAToZuKKN7zDu6a1ufQvrCcv+QtxrP//a+48k0r2T1qMQYP+1s/Xj1IeloxTv4BjOnTU1vquF66xwG/xQtwzP2IzIu9XFnt1Uu328tgIjKLKD5RxLHc5bif+4jUA127uNuOfUTCCQ/eWzwVbdOP9r6sPlZE8We5xA0/RWJakZwlhBCiVxIGOxdeT3wHv8H2aBw8eHYUVF65247vdu6yr+YS+fLbrEpcwHSPCbjN+DWZX9y6cFhObCBa54WbmwdTQ5ex9cKtadVH1hD5shduYyfg4hZA4pnOJkXFZP4JZrzixm3X8Ed9MaYsJ3TKE3T12t7dfanY+SHh/g3lmz5vGdublY+rxaQtns3UiQ11N3PV2TtyBl9Cp1wmJ/ds77ay9uqlJ9rLNStWnmLk4C7UuvUYiR+eZUb8AlxbS0CvW7lugyGDn5CzhBBC0NtjGK4do/CMFtexg3v1Ltt2eS+7r+lIzc8nyeNLUrKKGy8KB0laacbdmMdnh/NZ91I1pvdzG5/bXyBnVS6aedkcO1FE8bFcYkZ1cncuFWHGDfdBPVVR3dyXixkYEr/gmfhsPtufi3HsBX67LJuKhhSE7ct/TWafIFb/5SDFJ4r40+sjWqxixMSnqTpV/GCMZehqe/nvhkcIbgGLOTosiOlPdTpboHDtWip/voyIn97RoKz5RLpNwGWKjqVnJhA6Y7CcJYQQolcThrpKti9bTuHExejH9m4hNPZexCyeykB7B1xdnsJmtTY8lz+zhwNfHGTFHC/c3LyYueIg1Re/pLIO4AncPRw4mfIOKzbkY77che7s/7Fgsddib9dTJejevlQXHaTSTUfIWAc0/R145tUAxpwrpvgacK2IXcdGEBoTwMhH277z1jzqgNbyj4Zn+PdTd9rL40GsO1bEsfwNBP9zDfq1xZ1brt5K5SUrmr6t1EvTI4kD2SRMLGbpO1mNCZgQQkjC0Auq2ZWwiJT6BZgWe9x6Ptx7KQP0ufkv4HrjhQFwXsifTjQ86y4+UUTxtsW42jXM6bpwE3/6nY4hlj2sCA0idmcn77PttWit1Vjrem7/u7Uv9bdK3HKaDVt9X/p2NJbiqhWb9n/dg2PUe+1F87gLwb6uVH5xoXM9JX2eIPCdMNiwmNQv2kjO7Acz7edeOF78ojHBFEIISRh6/ORfsOLXmKxzMK3wZaDdfSzdT10YeSmXlNyzWNo46Wt/OpVg/Tvop4C5+HLn1vvU07jWmyn8smd3t6v74uDyNI5HMkgvtmKzVXN0fRal4zxw7w/Yu+A+rJgtKXuoaOftAfOJYrRjXHC4j8lCR+2lNGU2Hr5vs72NbMB2+RjpuWZGTOxCOR7zxRgzmG2G9ym42tpKKyn49CBVI1wYaicnCiGE6PmE4UIeppwvKN+5DL+mV9R83+doR3dpdXuI9ZiAy9RlFF5tfI6sz23oKm9vWrtX1AAMRi+q0xbg3bgvU5cda9zeQYxTG/dvkj8rLnsRN8elc2W0cyNwBmzNOHj7PtQdbNhPt8XsulZMYsAEXHRrKO2w7O3sS3tl/2kYxvn/xq4YX9ye05FwzoN4Q0DjRXMwwcY3cT3/EbOea2PQ49U9bN7jQPDMEb3bytqrl860l7pmvUZNrPlENg7mfHbeh5SOXULy7K6NN9B6LCZ+SuNjh7pm63WbgMvUeZgue/Pe2wH3MZkSQogHxyNKKdX0pbikjOFDn5Ja6YxrxSTOW4Z1wQaMz9k/hAWoZrthAZuHL2PjvK4nDH+rvMS/Ow2SdiCEENLDINrV34WY9+dQm5fdcQ/CA8hWnMW2/gtInjdCjqUQQogOSQ+D6BbpYRBCiO8X6WEQQgghhCQMQgghhJCEQQghhBCSMIgHlYxfEEIISRiEEEIIISRhEEIIIYQkDEIIIYSQhEEIIYQQkjAIIYQQQhIGIYQQQkjCIIQQQghJGIQQQgghCYMQQgghhCQMQgghhJCEQQghhBCSMAghhBDi/rC7LXv4wQ8oO/+l1IoQQggh2k4Yvv32W1ych0utCCGEEOI28khCCCGEEF1PGPRR0eijDKz/3NbqApZdiYTMCSHo5ieC+HwLYOPEB7MIWrubP2cWUNU4f1V+wh3zhxCdkkhEeObNebhayr4DpdzcYl0p699Kp6Su2YZtBbwXm8MlOWZC3DeXMvSEbChvc7ol30DI2vK739DpVPQrC7BIlYvvYJzcNVsh70WmcqLu3pbL7s4fTGFOBGW781xlAiFrKxt+/KaSM/WBbMmKYNi0GNKfLyB+mZVxdYX0jTfiYweUpZJQ6I7hEzeuLNOT/IQrK6ZocfQ1kD6tkPeWljNKe5ba+UZ0fXKI2FvOkbxUju/Yxf4KLRMDIhg1GRztAKxUlJVzBXC+uWdWKr6qxiZtUYhuO5emZ35G+yeyoXNMpIYOaX3idQu1bQZhNTtydnO81IzvNg2MDMHkV8nKTeaGuK2t5MwZ8PkokxVTtFjyjcxdW0jFRQsDnBzp29ed2I0Gnv8hMOJZBi5JIq/SkzlOctzEPY6TDRHM31zZ7jzOC9IxvezQ5Tix7U0g6MMCKi5a0Dg54jgkkIXjC1m5tpAr/R0Y2B8sf6/G5uBK2AepLBwNh1dFkHyo2QrrrVSUVZIXVMBATdOPGp7/TSoLtemEvJ5JRX0HhezjxOxVqYR1YRRCi4Qhfn0h1Vp3BvS3Z6BrMPNC3aj6UM+mMYEMa2st35h5781Uqh0DyVuRQFV5JftMW5g3JaLtZSoL2Xs+EJ8Fq4kd7YDGYsFm18p85ZlERG3hUr2FikobJQHb6QsM0yVimjNEWrYQXTAs1MSe0Lu8uWl+J5WfzpGhs9AN12D7PI0MOwN7DwTi2GyeVC/gqxzi3jfz3P/TE/aMFgCtr5Fcz+3oX6tkUUbjueKQkcnRBfT718azYJgfG9AwcVEaK3y1cgDFvYmTeansmdf4pdREwPsOrPsk+LZ23d040XgZyJ3sTnRYOQub2j0hDPp6Fuue3kLStGqyXzNgWZJKWGOybLloYdxbW4gdDZe2pVMyJgSfpkS6NIf1Vd6ETWmKjxDS80Mar80FRP98C5M2mtA53n29tDmGwXGannk/LiDmJT/0f53Gm/6NmdTpRAKmJ7H/kInVhYUkv+RHXGFfhnqG8OJwB5wne/KcLoYoVwvnq5rmT+C/DqeTvKOA9a94E5FjRfOTGURFBeMz2gENcG5TDPEHwHYgAd+ZBvLKdhE3M4I114JJzc0h/z9jeH5EKCm5OeS/PoIrV28djksbQhj9SjqXTpvwHRtB9tVOdhu1tdzVHCKmGNnXk909Hayzx8vQwbQdUe6M9ghEn1bastdml4HRzq4Md3Zl8ruFD2cZOmIxs+Y1P8aP9Sb+6N2XoTf0Rn12yd9z0Pv6MfUFP6a+4M3UX+VQAVScNlMF2Mwm9KaT9OvfcHG/VHiWAaMdqDCbOWEu5dzpHOJ+2fgo8lcm8k6Z2bEqmqA5ze6WzpZyaegIBjXbrNbHyJ787c0+OTeTBYl1iZN7Hid/r8T6uCPaHoqThnZ/kuqfuLZ9Q92a05nExRp4d20aye8aiMvYzZ8/MKD/bSrrP4xD/4aR7NLbF6nakcPJMYH4OPZMXbS4p589bST7124hecNZLuWbeUwXg+5qDvpf9SUhIRhnNAx9JZpRdVYeoxr7/qXs14xE97KZiLeq8VngyjmDgYpfmAhzBP5bw1BdNOPqqxlQV439j8v5o20EzvUJ6OcUMOBfGnKxmpohLAwGzaMG8id7E/9/tvPcfxh5vmkP2wnofvYa0NrTzx60fezp179z9d/d5XpDb5ShvWk+yYWMO5rI3Oh09gUn4NOsLTMtgdMlCVRlRjDrrw9pGTo6D+5LZf31YLbsD2GY9vvTJrrkR4GY8gMb7pbyDQQcdsARsBRkkpFvo8Rkxv93Jn7WeKczbLaBF1cYiEm7QK3DYCaGJpH0ScPyHEogqMCPrDddb9tEySEzg8ZHoHlY6uS7FusSJx0uV1VZjf3jT7TdRrsYJwDnDpnRjonoWkFHBhL7ZCVz91mx/KsDz3l549MXDu/bjcXihPNSA7qRzbs4zKzPqOYXK73R9lBdtOhhWLnZDK5+TOxvY9Q8A/NGa9C4x2AMdcXxh01zWbFhT9+braqQ5Le2M/RVb+yvO6GLj8C21kh20yOgeisWNPRtuvj3GcHCT3LIzUgl/ZNU0j9JJ3erEZ9H2ynRdRu2PppWD5q2vz2a/lq0WnsG9Ndi36dz9d/+ctUcWaVn6kR3RvtGk1F26/fs8Ia77+Eu7kx+JYE/N3vUVXXIRMRLzzbcobv48d7pzqyz4zJcytYz+QUDf67qfBk6WqfjeHecsXG9S632u1AGsF2z4TjC9baTYLvbu5pDxEsGkldGMHWCK6Nf0JNRauuwTZxLCSHi3QQCPJ4lZFU68QHPMjk8k3NNofN5KvqAZxnt4s7kV4xkl9t6tT67+xDi8GEzw8a7ogGcPZ3Y8XYOQ+MTCRvZLCK1Q5jz3hbefH4Ec5K3kKRrdoass7W8u7WZydt2lsMpEQS87Mf48Byq6u4mZiXWJU56KE7qSlnzy4ZegwBTIee36Bt7EPyYPHUWyZ/fRZzUmfljU7t/yZvJsemsjwxEv+UC/7XCD9+XQkj+3MyaVwOJ3lrddAHEcsiEfpMWnZ87/i87UbLVRPTiXTjr/Hhe54dllZ7kZi8rnNuUSMaFcv4YFYjvSy0/t9bdhbhSzZjP/FXNDQtXc2d4qEnBscqYlKLWZW1Te4sqVE3TTKdWqchFS1XCp1Xq0MdRKmp+kIr6OEUlZJ1Ueb8JUob9tUoppWqKtqq8klqlTq1S4YtilXFzhTq+JlZFLZypIrO2qijPqcp/9lylmz1X6YJnqkm6FFXWtI0bR5VRt1TtvaHUmd+HKy+f6crLy0MNG+miRnlOb/juM1MZdtaqXvH1VjV3jJvyWbJNldVUqb3x09WkJUdbznejRh3/XZDyWn6y8YfzarVuqorMrer+OttwMStSTfKKVXlXerCcN04q47QglVBU0+rkK5vDlVf80Ye6DK0vU6MOLZ+p/H9/vhttYpe62IU2Ufb7IDXKZ4Xau3OF8hozUxn371JGn0iV9bVSquaAMgRGqo2nalTtjRpVtjlSTQrbrK70an3WqLxFU9Ukz9Y//h+fbGWRXSrKJ0rl1Sh1cf1cpVtzVOUtmtmindfu/0D5B85UXs+4qUkzgpR/3DZ1RSl15g9RKnxhrFp9pKZF+xo3ZqZKOKmUqtmqIhduVVd2xiqf5SfVPSOxLnHSQbxkzZ+ujEXNv89UCadUt+PkSlakGjdmekO7L1mldHEHlFJKHVoepAz7lVKqSmXND1frKm5GlspbFKSS9leoK7VKlWWtUllfKqVuVKmLV5RSp9JU0s4qpf5RpWoaL4m1p1Ypfy8PNS6w2XW1eZ38fq7Sra/ocm20eCSR+KaBqkMJ6Mv9iIryRPNVARkZqZRY9Cz0ahzH4OBN2AwHHEliWKaBNU+GMLvaQOgpDUOvxRBhKuWMUwz5yRo4DfT3ZN4vnBhkl4DzNgMx14Ang0lsGvBRV0Dcq2fvSNbKyVum57HnTezJ12DJ1jMzoxL7yUZy7+jW7A0ae29i4/wYpoHHxgzBtteKDdBgoyTDiCFlNyXVDdmc1r/p5S8nJnk6kLHGQPzfA/Gf4c1YJ00n1tmxQToTh3Q9XEg7V+bNd2LWLz3J8E7idLL3XdTLQ1IGSw4Rzxo5/IQfiRuHdKNNeDNIAwM63SY0DA2YxSSn7diPCmTe5Cf4o8aGrQ4o3c2+swVkB3kS37QRJycq6preFuqN+tTys+Td/KwLS5zLTOPkZD0JWrjScALgZ78JIS/MSMZoE01jjzVTYsidEsOO2BDOh6WzcLiNfcl6NpyxAVaOpMZwJBU0w4NJfNMb7fgIFvqn3nq9Ghs1V61oHe3vaZe2xLrESZvqLnC+cgjOT97qOaqy2NNaE+1snDiOCbmj3Te0fcv/gHZA6z0Xtdc0cCGTuPSz2OotnFuRydpRIxnYr2meAkIyNUyMMBHmmIk+ajfjYubzWFrPvlfY4pFE8qdmzlfZqNmVRPhrEcxNLOSxoOhbyQJwxbyF+Kho9FHRxG09S43ZRMzm6wz895HMXm7gRScnfIKbnpvYqCndzso3GuaPyWh8xerydt6NjEb/q2j0v07lSGNfma1sO8lvJLDjmoYBoyMI89QAlWTnVvJiTDSjjmay454MsNFAn5v/4uaY16+2YDRV47NmF2UlZj6P92x2EtAw9vUt5CcHM9SyC+MrgUTnV3e8zvulrpRNGZX4f1LQqWThO1EGbSCpx3aTON7Mmpzye9AmQNOncf5/6Uu/2/YdGK3nLyVmypo+Ow2MtePBUZ7Ou9laFsx3v/1i5xTIitf7suG1aDJOt/HXEuqsVF12YF6cNwNd9US5OvHiOyE4VlY1XECGuzPujhPv+b9W8pjTvX6PUmJd4qQNV8s5X+fEsKbH5XXVVF114DGHu4iTVto9VHK+wpGhT7b+GLjK4sCwwBhM7wTjTDUWhyE4O9qjtW/6ODBwWiQLnwHL6QsMXGBi6eSeT7xbJAyWgnSyT1oZFWYgzMmGxdayrQ+cYcCUnIQpOYkVL49gwKgINv7BhOmXNt4LCCH7yRhin9HcbDwDfaNvzp84p+H5Dk/4sWR1EqaPkzB9FMHEpgERFgs8YyT3L6ks1bniaAeXMhPY9MMQwqZ4siCgmuQPdt+RnXVwh7QhhPEvJbCvJ/4KzHULtr72DHLQYCnbTnL2yRanAu1Ib+YsMhLlBSfNlT1yoNp6Dnd3qrFcdWLU6Hvzutq9LkObx13jwLinnbBWWXtmFzrRJlofxOTKqIs5rNlaiqXuQanPZr7aTvTCTLQLDOh+1HKy44wETHOsrHk1lLhdzS+WVkoyoglYWtCJeqgm761ZBLyayuFrF9j/uQMTx2u6vcsS6xInPVqf5Wc5P3QEQ5uSk3orVfVaHDR3GyeN7f6NhjcqbF99xr4+roxtbRzfN2cpsWm5khlNQNQ2Kr7RMic5/eY11ZSchClYy/FTDet29Dew9OWeTbqb2kjLtyRWZTJwl563cMJnSSrOB7aQ/NtAEq4Owf/NBGIdbZzPNhBxqLH/oLKSgQuqOZ6XyobscsYFTqOqwET8/w5mjp83ztg4n2ck5HMtGsBWVYrmFXf6Xs4hLtzMgD5AfRVnrk9jHqAZH0zU+JvpCyfS4ojJtidqXeO73bMNzPm/esKX2khc7MewH3Zc2AEODnCxkCMX4fnRd1lzwwMJn6zHON0TzeBn0T0zBk1Tj0ddAXHP6RteSbGzZ5B7IEuW9+Djk3oefvewDD163LvbJtrjGMiS5eW89WEEk99u6LZ11KVyKN69d+qzLJ2QhWmc6/APuoxk4ToTczT2jJufiK7ZycdWx827R9DgHJpK7uAczgxtvOWyFHLkZBXnxoSQFOfNmWXmDjbmgP9vU4l1BdsBI9NTPFnwowfkmH9PYl3i5A5HEwl4ezdWoPZaNVW2vsx8IbVxPRauVF/n+PRC+qHhxeU5xP64G3HSrN03/JVkE/1eSGr1NUub2cy5n3gS9qSFcev9uPJuMCc6nfCkEeKbc3uPDVBrrWZgWNfbSItBj0opdfEP4WruH24fEFHzZYm6WKOUKklRxqxb02pLdqm8jauU4eNt6szXTTOfV/nrV6msklqlStKUcWOzdRWlqdX7D6jV8VvVxWYDctb9btut703rLlqlwl9PUYfuHKxSU6I2/iZSJezvzACeWnVl51Ll4xmr8muUaF6NRR8of8+GwaWdGvT4UJWh/eNe+2mUGhe8Sh3/WtpB5yp6m4r0dFPjps1VSUXtDDauOanyPj2vapVSxz8OV7rgua1+Ijc2DKSrvdIwkEsppWqOpKl1++8mSCXWJU4ejjhp3u7VjfNqY3yKOvSPZgOTl8SqrL81fCvbGKWM+2tvHq/8RR7Ka3akinw96uYnfPZ0Nalx8GTzAaiRr6a1PuhxY6QK31zR5bhqNWFQN2pV7Y3vxvHbu2S6mhQYpVYXyRmkufxFbmrU5JkqcnOJatGsd8aqUSNd1LCRLmrSA5wwtFeGDo/7P06qdQunq3FjpirjEWkPEuvfz1iXOHkI3bh/cfWIUko1dTsUl5TJf28thBBCiBbkv7cWQgghRIfspApEpzzySNfmv9VxJYQQ4jtAehiEEEIIIQmDEEIIIe5ei0cSFotFakW0VFPTtfmlHQkhxHeK9DAIIYQQQhIGIYQQQkjCIIQQQogHMWEIDQ2VWhNCCCEkYZBkQQghhBDdTBgkWRBCCCEkYZBkQQghhBB3lzCkpaVJTQkhhBCSMEjSIIQQQogeSBgkaRBCCCG+vx5R6tZ/K1hcUsZTAx+XWhFCCCHEbeQPNwkhhBCiawmDRtNXakQIIYQQLfx/Rz8ee4/bqZsAAAAASUVORK5CYII=)

**Comment by Lucasgong** [comment]
旧版本试过啦，很好用，dalao太强啦！
目前没有十连寻访凭证和家具零件选项

**Comment by bbaa-bbaa** [comment]
其实有很多东西在精英化里面都没有用
所以就干脆就没有添加
龙门币等等的东西其实根本就没有参与运算

**Comment by Lucasgong** [comment]
嗯嗯，明白。
但不加的话，每次识图都要手动删去这些东西，不然就识别成其他的物品，数据就不对了。
