### ISSUE TITLE
关于如何加入的问题

### ISSUE THREAD

**Issue by ParticleG** [graueneko/aktools#41]
您好！非常感谢你们开发这个便利的平台！我听很多手机玩家反映说在手机上游戏和浏览器来回切换非常不方便；我现在打算做一个悬浮窗显示的webviewer，并且考虑通过图像识别直接在同一个页面导入数据。请问如何才能加入你们的开发团队？或者能否提供api交互的方式（）

**Comment by graueneko** [comment]
方便的话可以加TG群，不方便的话可以邮件与我联系：graueneko#gmail.com

其实本项目托管在Github Pages上，本质是静态页面，没有对外提供的API（因为原理上不支持）。

实现悬浮窗webview的话我不清楚具体实现，应该是安卓应用内嵌套页面的形式？这样其实不需要API。当然这只是我的猜想，如果有其他实现还请讨论。

**Comment by ParticleG** [comment]
悬浮窗webview我已经实现，我只是希望能和你们的网站对接（比如我发送带6个tag的json给服务器然后服务器把可能出的列表以json数组的列表返回给我），但是如果是静态页面的话就不行了。不过要是能提供没有顶栏的版本也可以，因为功能的切换选择和页面的更新可以通过我的客户端实现。（最好是有类似api接口的方式，因为这样我可以本地ocr识别再丢给你们的页面）
