### ISSUE TITLE
公开招募的问题 续

### ISSUE THREAD

**Issue by yuban01652** [graueneko/aktools#42]
大佬好，咱是上次那个建议让星级不加入清空的那个家伙
咱发现公开招募时，清空的确不会清空星级了，但搜索结果里仍会有排除的角色，比如我取消了2星，然后按清空，再搜索，结果仍会出现二星角色...电脑手机都是
另外今天晚上时为啥按清空会返回到首页了啊，下午还好着呢
谢谢大佬

**Comment by graueneko** [comment]
按清空返回首页是今晚某次更新后出现的bug，应该很快就修复了，如果还是出现请继续回复。

排除星级仍然出现这个应该是我实现的bug，稍后修复。
