### ISSUE TITLE
请教下公招组合右上角数字代表什么意思？

### ISSUE THREAD

**Issue by chenmt** [graueneko/aktools#47]
大佬你好，我是新入坑的方舟新人，想请问下工具箱中公开招募功能，计算出的每个组合右上角的数字代表什么意思？网上也查找不到相关内容，还望解答，谢谢。

**Comment by graueneko** [comment]
见 https://github.com/graueneko/aktools/issues/4#issuecomment-502968415
看来这个数字经常引起误解，我还是把这个数字去掉好了
