### ISSUE TITLE
希望能添加选择干员键盘快捷键

### ISSUE THREAD

**Issue by painttist** [graueneko/aktools#50]
虽然并不是很mobile friendly，但是如果能在网页版更快速选择的话就好了。我觉得可以考虑拼音首三个字母

**Comment by painttist** [comment]
我觉得可以考虑试试每个都用不同的组合，只要键盘输入就选中标签
新手：xin
资深：zi
高级资深: gao
远程：yc
近战：jz
男：nan
女：nv
先锋：xf
狙击：jj
医疗：yl
术士：ss
近卫：jw
重装：zz
辅助：fz
特种：tz
治疗：zl
支援：zy
输出：sc
群攻：qg
减速：js
生存：cu
防护：fh
削弱：xr
位移：wy
控场：kc
爆发：bf
召唤：zhao
复活：fu

**Comment by painttist** [comment]
我觉得另一种可能很可行的方式是每一个都是拼音的首两个字母。对于重复的，如生存和输出，就在打完 sc 后给一个tooltip，然后 sc1 就是生存，sc2 是输出 ，类似搜狗输入法

**Comment by graueneko** [comment]
很抱歉一直没有回复，最初看过后犹豫了下，后面忘记回复了……

这个功能我考虑了很久，最后还是没有加入，原因在于使用到的场景实在太少。

**Comment by painttist** [comment]
> 很抱歉一直没有回复，最初看过后犹豫了下，后面忘记回复了……
> 
> 这个功能我考虑了很久，最后还是没有加入，原因在于使用到的场景实在太少。

了解！可以理解
