### ISSUE TITLE
有没有考虑过加英文界面

### ISSUE THREAD

**Issue by Windsoldier76** [graueneko/aktools#56]
外服已经封测了，估计距离上线也不远了叭

**Comment by graueneko** [comment]
做外文（英日）界面不难，但我没有太多精力去维护外文的数据，可能暂时不会考虑。

实际上，也有人根据我的老版工具箱实现了英文版的，而且加了一些我没有做的东西：https://aceship.github.io/AN-EN-Tags/akhr.html
至少外文社区不会缺少这类工具了。
