### ISSUE TITLE
iPhone 7 公招计算器显示不全

### ISSUE THREAD

**Issue by wyf0638** [graueneko/aktools#57]
硬件: iPhone7, ios 10版本
公招界面，标签和干员结果页不显示，无法进行操作，不知道是不是个例

**Comment by graueneko** [comment]
@wyf0638 感谢反馈。

1. 可能是网络问题，国内的话请使用国内版本尝试
2. 若是界面bug请带一下截图

**Comment by wyf0638** [comment]
找了另一个iPhone 7试了下，没有问题，应该是我手机的系统问题
