### ISSUE TITLE
精英材料-刷图规划中是否可以添加地图过滤功能？

### ISSUE THREAD

**Issue by cnkei** [graueneko/aktools#58]
比如进度没推到或者信赖度阵容打不了某些关卡，希望能够在规划中设置一些过滤的地图

目前好像没有看到这样的功能，不知道好不好做，需要的话我也可以贡献代码

**Comment by graueneko** [comment]
刷图规划不是我做的，https://github.com/ycremar/ArkPlanner 你可以到这里发起issue。
