### ISSUE TITLE
开发新功能途中遇到的问题

### ISSUE THREAD

**Issue by Luke-lujunxian** [graueneko/aktools#6]
简单来说，我最近在试图为这个项目开发一个新功能：自动导入已有材料
技术设计大概是：

- [x] TensorFlow js + Yolov3-tiny做图像识别得到材料列表

- [x] 根据上一步网络定位截取图片

- [x] 数字OCR

- [x] 传到升级计算/精英材料（和已有功能类似）

然而没想到数字OCR这一步困难重重，我试过多种方法都没有成功实现

1. 神经网络（Yolo）识别数字：就是不知道为什么转换为TFJS之后就不出结果，我已经训练过两次，同样的图片在daeknet模型时几乎99%可信度但是转换过来什么结果也没有

2. JS OCR库（tesseract.js）：结果奇烂无比，调整图像也没有更好

3. 百度OCR API：提供50000次/天免费识别，结果还挺准的（团长？）。然而API请求要求POST而且不支持跨域……

就以上问题来看解决办法有两种
1. 找出 _问题1_ 的原因（具体难度我不知道，也许只是我犯了什么错）
2. 用服务器转发POST请求（似乎比较简单，然而我不会）

我也没啥新的想法了，各位如果想到什么欢迎提出来，我什么都会做的

**Comment by graueneko** [comment]
如果需要使用服务器转发代理，可以使用`https://rest.graueneko.xyz/proxy/+url`，这是我为了解决跨域问题自己搭建的Rest API（请勿滥用）。

例如，需向`https://api.abc.com/request`发起POST请求，可以直接向`https://rest.graueneko.xyz/proxy/https://api.abc.com/request`发起同样请求。

现在为了方便测试，允许所有来源的代理请求。服务器位于上海，代理百度云API没有问题。（由于VPS内存问题偶尔会无响应）

问题1我不是很熟悉，希望有人能提供帮助。

**Comment by Luke-lujunxian** [comment]
> 如果需要使用服务器转发代理，可以使用`https://rest.graueneko.xyz/proxy/+url`，这是我为了解决跨域问题自己搭建的Rest API（请勿滥用）。
> 
> 例如，需向`https://api.abc.com/request`发起POST请求，可以直接向`https://rest.graueneko.xyz/proxy/https://api.abc.com/request`发起同样请求。
> 
> 现在为了方便测试，允许所有来源的代理请求。服务器位于上海，代理百度云API没有问题。（由于VPS内存问题偶尔会无响应）
> 
> 问题1我不是很熟悉，希望有人能提供帮助。

感谢回复
我在进行转发请求的时候遇到了这样的回复
`{error_code: 100, error_msg: "Invalid parameter"}`
百度后台也没有请求记录，估计是由于请求中有参数？
`https://rest.graueneko.xyz/proxy/https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic?access_token=`

**Comment by graueneko** [comment]
如果收到了error_code，应该不是转发服务器的问题，而是请求参数的问题。

发送POST请求时，access_token可以放入request body内。
我用以下python代码测试没有问题，供参考（截取的任务界面）：

```python
import base64
import requests
with open("img.png","rb") as imgFile:
    encoded_str=base64.b64encode(imgFile.read()).decode('utf-8')

proxy="https://rest.graueneko.xyz/proxy/"
r=requests.post(proxy+"https://aip.baidubce.com/oauth/2.0/token",data={'grant_type':'client_credentials','client_id':'API_KEY','client_secret':'SECRET_KEY'})
access_token=r.json()['access_token']
r=requests.post(proxy+"https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic",data={
    'access_token': access_token,
    'image': encoded_str
},headers={
    'Content-Type':'application/x-www-form-urlencoded'
})
print(r)
print(r.json())
```

返回结果如下：
```
<Response [200]>
{'log_id': 8376111213329409636, 'words_result_num': 33, 'words_result': [{'words': 'N公uL'}, {'words': '24日常任务'}, {'words': '周常任务'}, {'words': '中主线任
务'}, {'words': 'reward set-000v'}, {'words': 'men累计收取1次制造站的制造产物'}, {'words': '点击领取'}, {'words': '500'}, {'words': 'reward set-o01v'}, {'words': 'emn完成1笔订单'}, {'words': '点击领取'}, {'words': 'reward set-o02v'}, {'words': 'requirement:让3名干员在宿舍中恢复体力'}, {'words': '点击领取'}, {'words': '1000'}, {'words': 'reward set-005v'}, {'words': '5'}, {'words': 'equirement)通关任意主线关卡3次'}, {'words': '0/3'}, {'words': 'reward set-004v'}, {'words': 'RHODESISIAND'}, {'words': '2000'}, {'words': 'reward set-00Sv'}, {'words': '发'}, {'words': 'requirement在主线关卡中击败1次敌方领袖'}, {'words': '0'}, {'words': '(@A'}, {'words': 'RHODESISIAND A'}, {'words': '5'}, {'words': 'reward set-006v'}, {'words': '发'}, {'words': 'meen累计击败任意200名敌兵'}, {'words': '0/200x'}]}
```

**Comment by graueneko** [comment]
感谢仓库检测功能~！

调整了一下界面，在加入上传的图片大小自适应后识别失效，猜测是因为直接使用的图片上的绝对坐标？不太清楚具体算法，是否可以修复一下？
已创建一个新分支，对界面做了一些优化：https://github.com/graueneko/aktools/tree/devel

**Comment by Luke-lujunxian** [comment]
确实是，在截图的时候会截不到数字的地方
原因应该是模型会给出的是缩放后的坐标，而截图函数的工作原理是将原图复制一份到canvas上再截取，导致了坐标图片不匹配的情况
现在我把img的属性改在<div>内，外面放了一个隐藏的img给模型和截图使用
