### ISSUE TITLE
我想请问一下所有功能都可以离线实现吗？

### ISSUE THREAD

**Issue by TwilightKHQ** [graueneko/aktools#61]
最近有点想用这个做个Android项目练练手，现在正在看看大概有哪些功能可以做到离线，
萌新不会弄服务器，不太好处理

**Comment by graueneko** [comment]
@TwilightKHQ 目前全部是离线项目，无后端。

**Comment by TwilightKHQ** [comment]
@graueneko ok 其他的基本都有思路了，
我想问一下 你们做的识别仓库材料是靠什么呀 代码看不懂/(ㄒoㄒ)/~~

**Comment by TwilightKHQ** [comment]
看到了相关提交的说明，目前暂时没接触过神经网络的内容，后面再学习一下/(ㄒoㄒ)/~~

**Comment by bbaa-bbaa** [comment]
> @graueneko ok 其他的基本都有思路了，
> 我想问一下 你们做的识别仓库材料是靠什么呀 代码看不懂/(ㄒoㄒ)/~~

图像前端识别用的是dHash对比
因为图像分割是我胡乱试出来的方法所以精度不高
等考完试了有空我去改改

**Comment by TwilightKHQ** [comment]
> > @graueneko ok 其他的基本都有思路了，
> > 我想问一下 你们做的识别仓库材料是靠什么呀 代码看不懂/(ㄒoㄒ)/~~
> 
> 图像前端识别用的是dHash对比
> 因为图像分割是我胡乱试出来的方法所以精度不高
> 等考完试了有空我去改改

我也找到了hash对比，不过看到的是phash，然后现在也不知道该怎么把图片分割做好
如果可以，找到了的话艾特我一下(～￣▽￣)～

**Comment by bbaa-bbaa** [comment]
> > > @graueneko ok 其他的基本都有思路了，
> > > 我想问一下 你们做的识别仓库材料是靠什么呀 代码看不懂/(ㄒoㄒ)/~~
> > 
> > 
> > 图像前端识别用的是dHash对比
> > 因为图像分割是我胡乱试出来的方法所以精度不高
> > 等考完试了有空我去改改
> 
> 我也找到了hash对比，不过看到的是phash，然后现在也不知道该怎么把图片分割做好
> 如果可以，找到了的话艾特我一下(～￣▽￣)～

有大佬说可以用聚类来做边界识别，但是一直没有时间去改，你可以去试试

**Comment by TwilightKHQ** [comment]
@bbaa-bbaa  我找到一种比较取巧的方法可以大致确定材料范围，识别结果已经通过邮件发给你，想请教一下有没有哪里可以改进的
