### ISSUE TITLE
无法显示刷图规划

### ISSUE THREAD

**Issue by ReisenZ** [graueneko/aktools#65]
点击刷图规划, 页面无返回数据. 跨域问题?
> Access to fetch at 'https://ak.inva.land/plan/' from origin 'https://aktoolscn.graueneko.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by graueneko** [comment]
我测试显示是正常的，可能是暂时网络问题。
