### ISSUE TITLE
关于合金与凝胶的BUG

### ISSUE THREAD

**Issue by shandian6033** [graueneko/aktools#68]
@graueneko 
1. 在精英材料页，新添加的炽合金，炽合金块，凝胶和聚合凝胶并不属于“精英材料”。
![明日方舟工具箱 by 一只灰猫](https://user-images.githubusercontent.com/20548601/72647043-8ed3e700-3945-11ea-9b02-4f20ad6991bf.png)

2. 并且“刷图规划”并不能计算新材料的获取途径
![明日方舟工具箱 by 一只灰猫](https://user-images.githubusercontent.com/20548601/72647136-cb074780-3945-11ea-9b47-f2b4de5b0eff.png)

ArkPlanner应该是支持新材料的获取的。希望能检查下
[https://github.com/graueneko/aktools/blob/master/src/app/material/material.component.ts](url)
第194行
`{ owned, required, exp_demand: false, extra_outc: false, gold_demand: false })`
required是否包含新材料

**Comment by graueneko** [comment]
已修复，感谢指出。
