### ISSUE TITLE
升级计算字有点看不清

### ISSUE THREAD

**Issue by AlephAlpha** [graueneko/aktools#71]
![Screenshot_2020-01-22 明日方舟工具箱 by 一只灰猫](https://user-images.githubusercontent.com/3600593/72863723-a11aa000-3d0c-11ea-935b-e7e3d083d42a.png)

能不能把文字换回黑色？

**Comment by Yue-plus** [comment]
待会改


 
---原始邮件---
发件人: "AlephAlpha"<notifications@github.com&gt;
发送时间: 2020年1月22日 11:46:46
收件人: "graueneko/aktools"<aktools@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [graueneko/aktools] 升级计算字有点看不清 (#71)




 
能不能把文字换回黑色？
