### ISSUE TITLE
暗色模式下样式问题

### ISSUE THREAD

**Issue by gaojr** [graueneko/aktools#72]
![image](https://user-images.githubusercontent.com/18600387/73170626-e0485700-4139-11ea-9eee-3acaa12e6dc8.png)

1. 下拉框全白
2. 技能名称、“保存并导入材料计算器”等文字是黑色的，在暗色模式下很难看清（下拉框、输入框在选择时便签也会变成黑色）
3. 加号减号是黑色的

> 2、3的问题仅在从亮色主题变为暗色主题后出现，如果直接加载暗色主题的页面是没有问题的

**Comment by graueneko** [comment]
第2/3问题很难修复，原因在于，主题切换后，动态加载的新主题的css渲染顺序错误。考虑到这仅在特殊情况下发生，不影响平时使用，因此暂时不考虑修复。
