### ISSUE TITLE
希望增加根据不同干员不同需求计算刷图路线的功能

### ISSUE THREAD

**Issue by Shwoft** [graueneko/aktools#83]
例如，精1 1级的夜莺升级到精2 1级
所需的龙门币，经验，材料
以及刷图规划
一共所需要的理智

**Comment by bbaa-bbaa** [comment]
此功能已经存在
配合“升级计算”与“干员材料”两功能使用”

**Comment by cnkei** [comment]
有这功能，干员材料

**Comment by graueneko** [comment]
这个界面实现起来过于复杂，不如分开计算，毕竟通常来说刷体力和金币只会去固定的地图。
