### ISSUE TITLE
自动导入 主线程切割数字 卡死

### ISSUE THREAD

**Issue by rbforelle** [graueneko/aktools#86]
![image](https://user-images.githubusercontent.com/29765197/74699041-e8a72580-51ff-11ea-8628-7e5dcded40c4.png)
问题如图，安卓10和win10上都有这个问题。win10上chrome已升级到最新版本80.0.3987.106

F12看到提示：
`<canvas _ngcontent-ggs-c1 style="margin:0 auto;" width="1920" height="1080">浏览器不支持Canvas 建议您换用最新版的Chrome/Firefox浏览器</canvas>`

`ERROR DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at i.MessageDeal (https://aktools.graueneko.xyz/main-es2015.15317ba7f49cdb9bea15.js:1:142306)
    at Worker.P (https://aktools.graueneko.xyz/polyfills-es2015.b00a8ee45d22faafa706.js:1:16003)
    at a.invokeTask (https://aktools.graueneko.xyz/polyfills-es2015.b00a8ee45d22faafa706.js:1:7012)
    at Object.onInvokeTask (https://aktools.graueneko.xyz/main-es2015.15317ba7f49cdb9bea15.js:1:92176)
    at a.invokeTask (https://aktools.graueneko.xyz/polyfills-es2015.b00a8ee45d22faafa706.js:1:6933)
    at s.runTask (https://aktools.graueneko.xyz/polyfills-es2015.b00a8ee45d22faafa706.js:1:2518)
    at c.invokeTask [as invoke] (https://aktools.graueneko.xyz/polyfills-es2015.b00a8ee45d22faafa706.js:1:8013)
    at y (https://aktools.graueneko.xyz/polyfills-es2015.b00a8ee45d22faafa706.js:1:20116)
    at Worker.k (https://aktools.graueneko.xyz/polyfills-es2015.b00a8ee45d22faafa706.js:1:20358)
We @ main-es2015.15317ba7f49cdb9bea15.js:1
handleError @ main-es2015.15317ba7f49cdb9bea15.js:1
next @ main-es2015.15317ba7f49cdb9bea15.js:1
l @ main-es2015.15317ba7f49cdb9bea15.js:1
__tryOrUnsub @ main-es2015.15317ba7f49cdb9bea15.js:1
next @ main-es2015.15317ba7f49cdb9bea15.js:1
_next @ main-es2015.15317ba7f49cdb9bea15.js:1
next @ main-es2015.15317ba7f49cdb9bea15.js:1
next @ main-es2015.15317ba7f49cdb9bea15.js:1
emit @ main-es2015.15317ba7f49cdb9bea15.js:1
(anonymous) @ main-es2015.15317ba7f49cdb9bea15.js:1
invoke @ polyfills-es2015.b00a8ee45d22faafa706.js:1
run @ polyfills-es2015.b00a8ee45d22faafa706.js:1
runOutsideAngular @ main-es2015.15317ba7f49cdb9bea15.js:1
onHandleError @ main-es2015.15317ba7f49cdb9bea15.js:1
handleError @ polyfills-es2015.b00a8ee45d22faafa706.js:1
runTask @ polyfills-es2015.b00a8ee45d22faafa706.js:1
invokeTask @ polyfills-es2015.b00a8ee45d22faafa706.js:1
y @ polyfills-es2015.b00a8ee45d22faafa706.js:1
k @ polyfills-es2015.b00a8ee45d22faafa706.js:1`

**Comment by bbaa-bbaa** [comment]
我看看...

**Comment by rbforelle** [comment]
> 我看看...

你回复的会不会有点太快了。。。

**Comment by bbaa-bbaa** [comment]
> > 我看看...
> 
> 你回复的会不会有点太快了。。。

能发张原图过来吗

**Comment by rbforelle** [comment]
对了，自动导入V2刚出来的时候是可以用的，可以自动设置识别数据也非常好。大概一天之后就切不出数字了，不知道为啥

**Comment by rbforelle** [comment]
> > > 我看看...
> > 
> > 
> > 你回复的会不会有点太快了。。。
> 
> 能发张原图过来吗

![MuMu20200105171326](https://user-images.githubusercontent.com/29765197/74699599-691a5600-5201-11ea-9762-e92295724400.png)

**Comment by rbforelle** [comment]
> > > 我看看...
> > 
> > 
> > 你回复的会不会有点太快了。。。
> 
> 能发张原图过来吗

和图片分辨率应当没什么关系，我手机上一样切不出数字。另外我一开始是可以用的，大概时间是2月14号11点的样子，后来最迟到2月15号8点我再试就这样了。
还有手机chrome上反复选择仓库图片识别之后，再点选择仓库图片进入选择图片界面以后会有几率卡死，手机重启才能恢复。目前因为自动导入不能工作我也不能复现这个问题。

下面附一张手机图片
![Screenshot_20200214-044252](https://user-images.githubusercontent.com/29765197/74699848-0ecdc500-5202-11ea-9dd6-263a05b6f7f1.jpg)

**Comment by bbaa-bbaa** [comment]
切图的问题已经定位了一正在修复

**Comment by bbaa-bbaa** [comment]
问题就是程序把那个消耗物品的剩余时间给识别成边框了
加了个范围限制解决了
等待灰猫大佬合并pr

**Comment by rbforelle** [comment]
> 问题就是程序把那个消耗物品的剩余时间给识别成边框了
> 加了个范围限制解决了
> 等待灰猫大佬合并pr
> ~借你的研磨石数据去添加了下不介意吧...~

哈哈随意的

**Comment by bbaa-bbaa** [comment]
最新版部署了，你可以去试试

**Comment by rbforelle** [comment]
完全ok~
