### ISSUE TITLE
自动导入 自己的识别数据未被应用

### ISSUE THREAD

**Issue by rbforelle** [graueneko/aktools#88]
自动导入识图错误，设置自己的识别数据后回到导入界面，依然无法识别。试过导出数据，复制，再导入，也一样没用。前一个我提交的issue修复之前似乎是好的。更新，清除缓存无法解决问题

在自己的识别数据那里可以识别：
![image](https://user-images.githubusercontent.com/29765197/74801483-0bf0d400-52d7-11ea-8a79-4c1af6271a64.png)

回到导入界面无法识别，特种芯片在右上：
![image](https://user-images.githubusercontent.com/29765197/74801532-30e54700-52d7-11ea-9c0a-0a17d8986b2b.png)

原图：
![MuMu20200219051235](https://user-images.githubusercontent.com/29765197/74801548-3d699f80-52d7-11ea-8391-d4ea351da79f.png)

**Comment by bbaa-bbaa** [comment]
已修复，等待PR合并
