### ISSUE TITLE
Feature request: Allow switching between EN/JP server for map plan (材料路径规划)

### ISSUE THREAD

**Issue by IbarakiKasen** [graueneko/aktools#92]
Thanks for your grinding planning tool! Recently I've found a map called SA-5 in the planning result. It seems that this is a event map that is currently available on CN server. However the events differs between CN and EN/JP. Is it possible to add a switch to allow us choose the server?

An alternative way I can think of is, a event list with switchs to include/exclude certain event maps. So that users from different servers can enable the current event they have. This also allows users to manually enable any future event they plan to grind on.

PS: It's ok to reply me in Chinese. 如果您需要此问题的中文翻译，请告诉我。

**Comment by graueneko** [comment]
Thank you for the advice.

Actually, the Arkplanner is maintained by another team, their homepage is https://planner.penguin-stats.io/ 

We show them your request, and they reply that this function is under development and will be available soon. We'll add the switch option ASAP.

**Comment by IbarakiKasen** [comment]
Thanks for the link. I've also gone through [their repo](https://github.com/ycremar/ArkPlanner/commits/master). It seems that their API https://planner.penguin-stats.io/plan/ already supports this feature. I can get my desired result by adding `"exclude":["SA-1","SA-2","SA-3","SA-4","SA-5","SA-6"]` to the posted json.
