### ISSUE TITLE
材料概率掉落期望与实际完全不符

### ISSUE THREAD

**Issue by Justin-Nickel-Wu** [graueneko/aktools#96]
进行干员精英化材料计算如果基于期望得到的结果往往过于乐观，导致刷图规划实用性极差（例如以1/3概率掉落理论三次即可，但实际上往往不止三次，普遍合成的效率大于直接拼脸的效率）。建议增加一个参数用于玩家根据自身欧气水平修正掉率再进行规划。再或者在刷图规划中去除概率向地图。

**Comment by bbaa-bbaa** [comment]
排除关卡功能已经存在
规划基于[企鹅物流数据统计的数据](https://penguin-stats.io/)的掉落数据
Arkplanner由另外的团队在进行维护 [项目主页](https://github.com/ycremar/ArkPlanner)

**Comment by graueneko** [comment]
这时 Arkplanner 的原理问题，他们使用数学期望的方式进行规划。

不相信规划结果的最好解决办法是：去专门的本刷。其实我还是使用的这种方法。
