### ISSUE TITLE
体力计算出错

### ISSUE THREAD

**Issue by xuziye0327** [graueneko/aktools#98]
![Annotation 2020-03-06 103516](https://user-images.githubusercontent.com/12589301/76044939-bb47cf00-5f96-11ea-9cdc-9ff65b6a5ffa.png)

**Comment by bbaa-bbaa** [comment]
可以提供需求数据么

**Comment by xuziye0327** [comment]
{"D32钢":[0,4],"双极纳米片":[4,4],"聚合剂":[0,0],"白马醇":[3,6],"扭转醇":[5,0],"三水锰矿":[4,5],"轻锰矿":[0,5],"五水研磨石":[4,0],"研磨石":[0,0],"RMA70-24":[0,0],"RMA70-12":[6,0],"提纯源岩":[0,0],"固源岩组":[0,8],"固源岩":[0,5],"源岩":[0,0],"改量装置":[0,0],"全新装置":[0,0],"装置":[0,6],"破损装置":[0,0],"聚酸酯块":[0,0],"聚酸酯组":[0,4],"聚酸酯":[0,13],"酯原料":[0,0],"糖聚块":[0,0],"糖组":[0,11],"糖":[0,11],"代糖":[0,4],"异铁块":[0,0],"异铁组":[0,5],"异铁":[0,16],"异铁碎片":[0,5],"酮阵列":[0,0],"酮凝集组":[0,0],"酮凝集":[0,9],"双酮":[0,0],"炽合金块":[0,0],"聚合凝胶":[0,0],"炽合金":[0,0],"凝胶":[0,0],"技巧概要·卷3":[0,16],"技巧概要·卷2":[0,48],"技巧概要·卷1":[0,15],"芯片助剂":[0,0],"先锋双芯片":[0,0],"先锋芯片组":[0,0],"先锋芯片":[0,0],"近卫双芯片":[0,4],"近卫芯片组":[0,0],"近卫芯片":[0,5],"重装双芯片":[0,4],"重装芯片组":[0,0],"重装芯片":[0,5],"狙击双芯片":[0,0],"狙击芯片组":[0,0],"狙击芯片":[0,0],"术师双芯片":[0,0],"术师芯片组":[0,0],"术师芯片":[0,5],"医疗双芯片":[0,0],"医疗芯片组":[0,0],"医疗芯片":[0,0],"辅助双芯片":[0,0],"辅助芯片组":[0,0],"辅助芯片":[0,0],"特种双芯片":[0,0],"特种芯片组":[0,0],"特种芯片":[0,0]}

**Comment by bbaa-bbaa** [comment]
暂时无法复现这个bug
[可能的原因](https://github.com/ycremar/ArkPlanner/issues/19)
请不要在打开需求龙门币或狗粮的同时排除LS-*/CE-*关卡

**Comment by xuziye0327** [comment]
![image](https://user-images.githubusercontent.com/12589301/76061630-e6deaf80-5fbe-11ea-869f-82a950296374.png)

**Comment by xuziye0327** [comment]
上面数据结果也不正确
![image](https://user-images.githubusercontent.com/12589301/76061738-273e2d80-5fbf-11ea-8d17-4a128d087207.png)

**Comment by bbaa-bbaa** [comment]
嗯，有空我去看下

**Comment by xuziye0327** [comment]
> {"D32钢":[0,4],"双极纳米片":[4,4],"聚合剂":[0,0],"白马醇":[3,6],"扭转醇":[5,0],"三水锰矿":[4,5],"轻锰矿":[0,5],"五水研磨石":[4,0],"研磨石":[0,0],"RMA70-24":[0,0],"RMA70-12":[6,0],"提纯源岩":[0,0],"固源岩组":[6,8],"固源岩":[15,5],"源岩":[0,0],"改量装置":[0,0],"全新装置":[0,0],"装置":[3,3],"破损装置":[3,0],"聚酸酯块":[0,0],"聚酸酯组":[9,4],"聚酸酯":[6,13],"酯原料":[2,0],"糖聚块":[0,0],"糖组":[2,11],"糖":[0,11],"代糖":[21,4],"异铁块":[0,0],"异铁组":[0,5],"异铁":[1,8],"异铁碎片":[5,5],"酮阵列":[0,0],"酮凝集组":[4,0],"酮凝集":[0,9],"双酮":[12,0],"炽合金块":[0,0],"聚合凝胶":[0,0],"炽合金":[0,0],"凝胶":[0,0],"技巧概要·卷3":[17,16],"技巧概要·卷2":[4,48],"技巧概要·卷1":[120,10],"芯片助剂":[0,0],"先锋双芯片":[0,0],"先锋芯片组":[0,0],"先锋芯片":[0,0],"近卫双芯片":[0,4],"近卫芯片组":[0,0],"近卫芯片":[0,5],"重装双芯片":[0,4],"重装芯片组":[0,0],"重装芯片":[0,5],"狙击双芯片":[0,0],"狙击芯片组":[0,0],"狙击芯片":[0,0],"术师双芯片":[0,0],"术师芯片组":[0,0],"术师芯片":[0,0],"医疗双芯片":[0,0],"医疗芯片组":[0,0],"医疗芯片":[0,0],"辅助双芯片":[0,0],"辅助芯片组":[0,0],"辅助芯片":[0,0],"特种双芯片":[0,0],"特种芯片组":[0,0],"特种芯片":[0,0]}
> ![image](https://user-images.githubusercontent.com/12589301/76061738-273e2d80-5fbf-11ea-8d17-4a128d087207.png)

![image](https://user-images.githubusercontent.com/12589301/76107424-95144480-6013-11ea-890d-c0122da0a826.png)

**Comment by bbaa-bbaa** [comment]
由于planner的对龙门币的计算需要，在需求大量龙门币时排除掉落龙门币的关卡会导致计算错误
我已经在可屏蔽列表中吧这些关卡去掉了
但是要等待喵佬合并PR……
临时解决方案把S5-2和S6-4勾上...
